version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tplink-webui-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - tplink-webui

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tplink-webui-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tplink-webui

networks:
  tplink-webui:
    driver: bridge

volumes:
  logs:
  data: